# Generated by Django 5.2.5 on 2025-09-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuname', models.CharField()),
                ('stuage', models.IntegerField()),
                ('stugernder', models.CharField()),
                ('stusub', models.CharField()),
                ('stumock', models.BooleanField()),
            ],
        ),
    ]
