# Generated by Django 5.2.5 on 2025-09-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stumarks',
            field=models.FloatField(default=0),
        ),
    ]
