# Generated by Django 5.2.5 on 2025-09-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_student_stumarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stumarks',
            field=models.BigIntegerField(verbose_name='9080183671'),
        ),
    ]
